# This file can only be edited inside the uBlue image's git repository.

# The image will be at "ghcr.io/yourusername/name".
name: ublue-sapphypr
# The native container image to build on top of.
# Warning: Non-uBlue images might not work properly, due to missing components.
base-image: ghcr.io/ublue-os/base-main
# What Fedora version to use. Use an explicit version or `latest`.
# If you use `latest`, you will be automatically updated to the next major
# Fedora version, assuming the image you're using as your base container
# builds with the tag (all uBlue images do this).
fedora-version: 38
# This description will be visible in the container metadata.
description: A custom experimental fedora silverblue/kinote OCI image, based on ublue-os with the hyprland wayland compositor.
# These scripts will be executed during the container build.
# Place scripts in the "scripts/" dir and put the corresponding filenames here.
# Any files that aren't listed here won't be executed automatically, which
# means that you can place "helper" or "library" scripts in the folder too.
# You can use "autorun.sh" if you want an automatic runner.
scripts:
  # "Pre" scripts run very early in the build, immediately after your custom
  # repos have been imported (so that you can access those repos if necessary).
  pre:
    # Automatically runs script files within "scripts/pre/".
    - autorun.sh
    # Manually listed scripts.
    # - example_pre.sh
  # "Post" scripts run at the end of the build process.
  post:
    # Automatically runs script files within "scripts/post/".
    - autorun.sh
    # Manually listed scripts.
    # - example_post.sh
# Custom RPM configuration.
# These changes will be integrated into your custom image at the "system level".
rpm:
  # A list of urls of ".repo" files that should be added to your system.
  # This is the proper way to add custom COPR repos to your image.
  # Tip: Use `%FEDORA_VERSION%` instead of static Fedora version numbers,
  # so that your repos automatically use your image's actual Fedora version,
  # which greatly simplifies future maintenance of your custom recipe.
  repos:
  # Example (which also demonstrates version number expansion):
  # - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%FEDORA_VERSION%/atim-starship-fedora-%FEDORA_VERSION%.repo
    - https://copr.fedorainfracloud.org/coprs/solopasha/hyprland/repo/fedora-%FEDORA_VERSION%/solopasha-hyprland-fedora-%FEDORA_VERSION%.repo
    - https://packages.microsoft.com/yumrepos/vscode/config.repo
    - https://copr.fedorainfracloud.org/coprs/kylegospo/gnome-vrr/repo/fedora-%FEDORA_VERSION%/kylegospo-gnome-vrr-fedora-%FEDORA_VERSION%.repo
    - https://copr.fedorainfracloud.org/coprs/kylegospo/system76-scheduler/repo/fedora-%FEDORA_VERSION%/kylegospo-system76-scheduler-fedora-%FEDORA_VERSION%.repo
  # These RPMs will be installed from your enabled repositories (Fedora's own
  # repos, extra "repos" you've added, etc). The installation is automatically
  # performed via rpm-ostree during the image build, and will be pre-installed
  # at the "system level" in the final image.
  install:
  # Base
  - libadwaita
  - python3-pip

  # Audio
  - pipewire
  - pipewire-alsa
  - pipewire-gstreamer
  - pipewire-jack-audio-connection-kit
  - pipewire-plugin-libcamera
  - pipewire-pulseaudio
  - wireplumber

  # Core Hyprland
  - hyprland
  - hyprland-autoname-workspaces
  - hyprland-plugins
  - hyprpicker
  - mako
  - pam-u2f
  - pamu2fcfg
  - polkit-kde
  - qt5-qtwayland
  - qt5ct
  - greetd
  - swaybg
  - swayidle
  - swaylock
  - wlsunset
  - wlr-randr
  - wlogout
  - wofi
  - wtype
  - xdg-desktop-portal-hyprland

  # Network
  - NetworkManager-adsl
  - NetworkManager-bluetooth
  - NetworkManager-iodine-gnome
  - NetworkManager-l2tp-gnome
  - NetworkManager-libreswan-gnome
  - NetworkManager-openconnect-gnome
  - NetworkManager-openvpn-gnome
  - NetworkManager-ppp
  - NetworkManager-pptp-gnome
  - NetworkManager-vpnc-gnome
  - NetworkManager-wifi
  - NetworkManager-wwan

  # Optimizations
  - gamescope
  - system76-scheduler

  # Software
  - code
  - thunar

  # System Utilities
  - btop
  - cronie
  - git
  - zsh
  - blueman

  # These RPMs will be removed from the system image. This step happens during
  # image build, BEFORE installing custom RPMs (from the "rpm.install" category).
  remove:
    # Remove the native firefox (from Fedora) in favor of the Flatpak.
    - firefox
    - firefox-langpacks
# Configuration for the "first boot" experience, which is available after login.
firstboot:
  # Whether to embed "yafti" into the OS image and configure it to autostart,
  # which is the preferred uBlue "first boot" GUI. Set this to "false" if you've
  # decided to use a different solution instead.
  yafti: true
  # These Flatpaks will be suggested for install after user login, via the yafti
  # "first boot" GUI. Everything below will be merged into the "yafti.yml" config
  # on build, in a category named "Custom". If you prefer, you can instead remove
  # everything below and directly edit "yafti.yml" to have more control.
  # Alternatively, if you've disabled "yafti", you can still install these via
  # the "just setup-flatpaks" command from our "custom.just" template file.
  # This is just an example selection:
  flatpaks:
    #
